// @index('./**/*.svelte', f => `export * from '${f.path}.svelte'`)
export * from './AddIcon.svelte';
export * from './bookIcon.svelte';
export * from './BronzeMedal.svelte';
export * from './category.svelte';
export * from './dislike.svelte';
export * from './Empty.svelte';
export * from './fireIcon.svelte';
export * from './GoldMedalIcon.svelte';
export * from './like.svelte';
export * from './MapIcon.svelte';
export * from './pageIcon.svelte';
export * from './PoundIcon.svelte';
export * from './quote.svelte';
export * from './rankIcon.svelte';
export * from './ranking.icon.svelte';
export * from './SilverIcon.svelte';
export * from './SiteIcon.svelte';
export { default as Spinner } from './loader/Spinner.svelte';
export { default as OvalSpinner } from './loader/oval.svelte';
export * from './StarIcon.svelte';
export * from './Trophy.svelte';
export * from './viewicon.svelte';
export * from './WordCountIcon.svelte';
export { default as X } from './XIcon.svelte';
export { default as Check } from './CheckIcon.svelte';
