// Generated by Wrangler by running `wrangler types`

export interface Env {
	kv_cache: KVNamespace;
	KV_PREVIEWS: KVNamespace;
	KV_CHAPTER: KVNamespace;
	API_HOST: 'example.com';
	API_ACCOUNT_ID: 'example_user';
	SERVICE_X_DATA: { URL: 'service-x-api.dev.example'; MY_ID: 123 };
	NODE_VERSION: '18.20.2';
	do_throttler: DurableObjectNamespace /* counter from durable-objects */;
	do_statsCounter: DurableObjectNamespace /* statsCounter from stats-counter */;
	do_EmailCounter: DurableObjectNamespace /* EmailCounter from beta-review-invitation-email-counter */;
	chatroom: DurableObjectNamespace /* ChatRoom from chatroom */;
	do_httpsAlarmScheduler: DurableObjectNamespace /* Scheduler from http-invocation-scheduler */;
	do_BookAlarm: DurableObjectNamespace /* BookStatsScheduler from book-stats-scheduler */;
	LOG_BUCKET: R2Bucket;
	R2_Image: R2Bucket;
	images: R2Bucket;
	DB: D1Database;
	PREVIEW_LINKS: AnalyticsEngineDataset;
	BOOK_REFERRER: AnalyticsEngineDataset;
	BOOKS: AnalyticsEngineDataset;
	MY_RATE_LIMITER: RateLimit;
	'counter-queue': Queue;
	COUNTER_QUEUE: Queue;
	BOOKS_STREAM_QUEUE: Queue;
	HYPERDRIVE: Hyperdrive;
}
